spring.profiles.active=local
server.port=8080

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/licencias_db
spring.datasource.username=codespace
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads/
app.nombre=Municipalidad - Licencias de Funcionamiento
app.pago.tramite=180.00
app.pago.renovacion=180.00
app.inspeccion.dias-habiles=30
app.licencia.vigencia-dias=365
app.licencia.alerta-dias-1=30
app.licencia.alerta-dias-2=7
server.forward-headers-strategy=framework
factiliza.token=${FACTILIZA_TOKEN}

# Factiliza API

# Flow Pagos
flow.api.key=${FLOW_API_KEY:77C4176F-046D-46D2-94E6-4DC8LB148D9E}
flow.secret.key=${FLOW_SECRET_KEY:80da2f6a077f343eb4c9d4879c874d216bb468ff}
flow.api.url=${FLOW_API_URL:https://www.flow.cl/api}

# Zona horaria Peru
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:demo}
cloudinary.api-key=${CLOUDINARY_API_KEY:demo}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:demo}

resend.api-key=${RESEND_API_KEY:re_SwXMmB5L_PxGAmpVsvuPzvD3anXzpwJyJ}
resend.from=onboarding@resend.dev
