# ── Producción (Render) ────────────────────────────────────────────────────────
# Las variables de entorno se configuran en el dashboard de Render

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.thymeleaf.cache=true

app.upload.dir=/tmp/uploads/
factiliza.api.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MTA2MyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImNvbnN1bHRvciJ9.kScxSHyCH622GK3-0IwV_HmHKl136TG6qnYFuVXG758

spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

resend.api-key=${RESEND_API_KEY:re_SwXMmB5L_PxGAmpVsvuPzvD3anXzpwJyJ}
resend.from=onboarding@resend.dev
